#### World Trade with USA



##### Guy Georges Mendi

***********
## EXECUTIVE SUMMARY

This project launches a quick glance at the US International Trade.

For many countries and businessmen have access to the value of trade between a country and the United States, may have advantages in the development of business strategy. 

This simple app provides an unique opportunity for the viewers to search for historical trade deficit/surplus between USA and a given country, from 2007 till 2013. 

Searched information deficit/surplus are displayed by selecting the year by hovering the mouse cursor over the graph.
Principal products and their value are summarized in table output format under 'Data' tab. 

(Data source: United Nation COMTRADE Database http://comtrade.un.org/data/)

***********
###### To view Trade Deficit/Surplus Between USA and a country

You first have to choose the year by hovering the mouse cursor, then you choose a country:

***********
###### To view the main products imported by USA in a country

You first have to choose the year by hovering the mouse cursor, then you choose a country, and a Trade Flow="Import":

***********
###### To view the main products exported by USA in a country

You first have to choose the year by hovering the mouse cursor, then you choose a country, and a Trade Flow="Export":

You can make the same thing with Re-exportations, to view main item which are rexportated in USA.
